spring:
  application.name: hanghae-concert
  profiles.active: local
  config:
    import:
      - db-core.yml
      - message-broker-core.yml

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

---
spring.config.activate.on-profile: local



